name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  redstonelimiter:
    aliases: ["redstone"]
    description: "Check the amount of redstone toggled."